//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atracciones
    {
        public long id_atraccion { get; set; }
        public long id_ciudad { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public byte[] itinerario { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
