
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullViajes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ciudad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ciudad()
    {

        this.Alojamiento = new HashSet<Alojamiento>();

        this.Atracciones = new HashSet<Atracciones>();

        this.Clima = new HashSet<Clima>();

        this.Imagen = new HashSet<Imagen>();

    }


    public long id_ciudad { get; set; }

    public string nombre { get; set; }

    public string cp { get; set; }

    public string coordenadas { get; set; }

    public string descripcion { get; set; }

    public Nullable<bool> menu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Alojamiento> Alojamiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Atracciones> Atracciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Clima> Clima { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Imagen> Imagen { get; set; }

}

}
