
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullViajes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Clima
{

    public long id_clima { get; set; }

    public long id_ciudad { get; set; }

    public System.DateTime fecha { get; set; }

    public string estado { get; set; }

    public short tempmax { get; set; }

    public short tempmin { get; set; }



    public virtual Ciudad Ciudad { get; set; }

}

}
