

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullViajes.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FullViajesEntities : DbContext
{
    public FullViajesEntities()
        : base("name=FullViajesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Alojamiento> Alojamiento { get; set; }

    public virtual DbSet<Atracciones> Atracciones { get; set; }

    public virtual DbSet<Ciudad> Ciudad { get; set; }

    public virtual DbSet<Clima> Clima { get; set; }

    public virtual DbSet<Imagen> Imagen { get; set; }

    public virtual DbSet<Respuestas> Respuestas { get; set; }

    public virtual DbSet<Topicos> Topicos { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

}

}

