
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullViajes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Imagen
{

    public long id_imagen { get; set; }

    public long id_ciudad { get; set; }

    public string url { get; set; }

    public string descripcion { get; set; }

    public short seccion { get; set; }



    public virtual Ciudad Ciudad { get; set; }

}

}
