//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        public long id_respuesta { get; set; }
        public long id_topics { get; set; }
        public long id_usuario { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Topicos Topicos { get; set; }
    }
}
