
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FullViajes.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuario()
    {

        this.Respuestas = new HashSet<Respuestas>();

        this.Topicos = new HashSet<Topicos>();

    }


    public long id_usuario { get; set; }

    public string nickname { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public byte rol { get; set; }

    public string user_foto { get; set; }

    public string user_descripcion { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public Nullable<bool> active { get; set; }

    public string token { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Respuestas> Respuestas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Topicos> Topicos { get; set; }

}

}
